test:stable:
  image: jimmycuadra/rust

  tags:
    - docker

  variables:
    CARGO_HOME: "/source/.cargo"

  script:
    - ./ci/test_with_crates.sh

test:nightly:

  image: schickling/rust

  tags:
    - docker

  variables:
    CARGO_HOME: "/source/.cargo"

  script:
    - ./ci/test_with_crates.sh
