test:stable:
  image: rust
  cache:
    paths:
      - target/
      - cargo/
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  script:
    - apt-get update -qy
    - apt-get install -y fuse libfuse-dev
    - rustc --version && cargo --version
    - cargo test --verbose --jobs 1 --all

test:nightly:
  allow_failure: true
  image: rustlang/rust
  cache:
    paths:
      - target/
      - cargo/
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  script:
    - apt-get update -qy
    - apt-get install -y fuse libfuse-dev
    - rustc --version && cargo --version
    - cargo test --verbose --jobs 1 --all
