test:stable:
  image: jimmycuadra/rust
  tags:
    - gitlab-org
  cache:
    paths:
      - target/
      - cargo/
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  script:
    - rustc --version && cargo --version
    - ./ci/test_with_crates.sh

test:nightly:
  allow_failure: true
  image: schickling/rust
  tags:
    - gitlab-org
  cache:
    paths:
      - target/
      - cargo/
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  script:
    - rustc --version && cargo --version
    - ./ci/test_with_crates.sh
