test:stable:
  image: jimmycuadra/rust
  cache:
    paths:
      - target/
      - merkle/target/
      - cargo/
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  script:
    - rustc --version && cargo --version
    - cargo --verbose --jobs 1 --all

test:nightly:
  allow_failure: true
  image: schickling/rust
  cache:
    paths:
      - target/
      - merkle/target/
      - cargo/
  variables:
    CARGO_HOME: $CI_PROJECT_DIR/cargo
  script:
    - rustc --version && cargo --version
    - cargo test --verbose --jobs 1 --all
