language: rust

os:
    - linux
    - osx

rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: nightly

cache:
    directories:
        - $HOME/.cargo
        - target
        - merkle/target

script:
    - rustc --version && cargo --version
    - ./ci/test_with_crates.sh