language: rust

os:
    - linux
    - osx

rust:
    - stable
    - beta
    - nightly

matrix:
    allow_failures:
        - rust: nightly

cache:
    directories:
        - $HOME/.cargo
        - target

before_install:
  - brew update
  - brew cask install osxfuse

script:
    - rustc --version && cargo --version
    - cargo test --verbose --jobs 1 --all
