language: rust

os:
  - linux
  - osx

rust:
  - stable
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache:
  directories:
    - $HOME/.cargo
    - target

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y fuse libfuse-dev; else brew update && brew cask install osxfuse; fi

script:
  - rustc --version && cargo --version
  - cargo test --verbose --jobs 1 --all
