[package]
name = "deneb"
version = "0.1.0"
authors = ["Radu Popescu <mail@radupopescu.net>"]

[[bin]]
name = "deneb"
doc = false

[dependencies]
clap = "^2.21.0"
chrono = "^0.3.0"
error-chain = "^0.10.0"
fuse = "^0.3.0"
log = "^0.3.0"
log4rs = "^0.7.0"
nix = "^0.8.0"
rust_sodium = "^0.2.0"
time = "^0.1.0"

[dev-dependencies]
notify = "^4.0.0"
quickcheck = "^0.4.0"
