[package]
name = "deneb"
version = "0.1.0"
authors = ["Radu Popescu <mail@radupopescu.net>"]

[dependencies]
clap = "~2.19.0"
time = "0.1.35"
rust-crypto = "~0.2.36"

merkle = {path = "merkle", version = "~0.1.0"}
