[package]
name = "deneb"
version = "0.1.0"
authors = ["Radu Popescu <mail@radupopescu.net>"]

[features]
default = ["fuse_module", "watcher"]
fuse_module = ["fuse"]
watcher = ["notify"]

[[bin]]
name = "deneb"
path = "src/main.rs"
doc = false
required-features = ["fuse_module"]

[[bin]]
name = "bincode"
doc = false

[[bin]]
name = "lmdb"
doc = false

[[bin]]
name = "loop"
doc = false

[[bin]]
name = "mmap"
doc = false

[[bin]]
name = "watcher"
doc = false
required-features = ["watcher"]

[dependencies]
bincode = "^0.8.0"
clap = "^2.21.0"
data-encoding = "^2.0.0-rc.1"
error-chain = "^0.10.0"
futures = "^0.1.14"
lmdb = "^0.7.0"
lmdb-sys = "^0.7.0"
log = "^0.3.0"
log4rs = "^0.7.0"
memmap = "0.5.2"
nix = "^0.8.0"
rust_sodium = "^0.3.0"
serde = "^1.0.8"
serde_bytes = "^0.10.0"
serde_derive = "^1.0.8"
time = "^0.1.0"
tokio-core = "^0.1.8"
toml = "^0.4.0"

fuse = { version = "^0.3.0", optional = true}
notify = { version = "^4.0.0", optional = true }

[dev-dependencies]
copy_dir = "^0.1.2"
quickcheck = "^0.4.0"
rand = "^0.3.15"
tempdir = "^0.3.5"
uuid = { version = "^0.5.0", features = ["v4"]}

