[package]
name = "deneb"
version = "0.1.0"
authors = ["Radu Popescu <mail@radupopescu.net>"]

[dependencies]
clap = "^2.20.0"
time = "^0.1.0"
rust-crypto = "^0.2.0"
merkle = {path = "merkle", version = "^0.1.0"}

[workspace]
members = ["merkle"]
