[package]
name = "deneb"
version = "0.1.0"
authors = ["Radu Popescu <mail@radupopescu.net>"]

[features]
default = ["fuse_module"]
fuse_module = ["fuse"]
watcher = ["notify"]

[[bin]]
name = "deneb"
doc = false
required-features = ["fuse_module"]

[[bin]]
name = "watcher"
doc = false
required-features = ["watcher"]

[dependencies]
clap = "^2.21.0"
error-chain = "^0.10.0"
log = "^0.3.0"
log4rs = "^0.7.0"
nix = "^0.8.0"
rust_sodium = "^0.2.0"
time = "^0.1.0"

fuse = { version = "^0.3.0", optional = true}
notify = { version = "^4.0.0", optional = true }

[dev-dependencies]
copy_dir = "^0.1.2"
quickcheck = "^0.4.0"
rand = "^0.3.15"
tempdir = "^0.3.5"
uuid = { version = "^0.5.0", features = ["v4"]}

