[package]
name = "deneb-common"
version = "0.1.0"
authors = ["Radu Popescu <mail@radupopescu.net>"]

[dependencies]
failure = "^0.1.0"
log = "^0.4.0"
log4rs = "^0.8.0"
nix = "^0.9.0"
structopt = "0.1.0"
structopt-derive = "0.1.0"
time = "^0.1.0"
